# -*- coding: utf-8 -*-
"""Training-and-deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CNbL98vzKVquy-L2hgIc6YLna7Hnw5t

Because this is a fresh notebook, I have to reinstall Unsloth, Whisper, and Gradio. I also mount Google Drive immediately. I wrapped the Drive mount in a check so it doesn't throw annoying errors if I accidentally run the cell twice.
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# 1. Mount Drive securely
from google.colab import drive
if not os.path.exists('/content/drive/MyDrive'):
    print("Mounting Google Drive...")
    drive.mount('/content/drive')
else:
    print("Google Drive is already mounted.")

# 2. Install required dependencies
print("Installing Unsloth, Whisper, and Gradio...")
!pip install unsloth
!pip install --no-deps xformers trl peft accelerate bitsandbytes
# FIX: Swapped standard openai-whisper for faster-whisper to allow INT8 memory compression!
!pip install faster-whisper gradio
!sudo apt-get install ffmpeg -y
print("Environment setup complete.")

""" I have upgraded this pipeline to use the massive 9-Billion parameter Gemma model for maximum linguistic accuracy. To make this notebook "Run All" friendly, I wrote logic to check if my trained weights already exist in Google Drive. If they do, it instantly loads my custom brain so I don't have to train again. If they don't, it loads the base Gemma 9B model and attaches blank LoRA adapters ready for learning."""

from unsloth import FastLanguageModel
import torch
import os

max_seq_length = 2048
dtype = None
save_path = "/content/drive/MyDrive/ph_stutter_smoother_lora"

# Check if we already trained the model previously
if os.path.exists(save_path):
    print(f"Found trained weights at {save_path}!")
    print("Loading custom 9B model...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = save_path,
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = True,
    )
    is_trained = True
    print("✅ Custom trained model loaded successfully.")
else:
    print("No trained weights found. Downloading quantized base Gemma 9B model (Best Accuracy)...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        # FIX: Pointing to the exact, official pre-quantized 4-bit HuggingFace repo to prevent 404 errors
        model_name = "unsloth/gemma-2-9b-it-bnb-4bit",
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = True,
    )

    # Apply blank LoRA adapters
    model = FastLanguageModel.get_peft_model(
        model,
        r = 16,
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                          "gate_proj", "up_proj", "down_proj"],
        lora_alpha = 16,
        lora_dropout = 0,
        bias = "none",
        use_gradient_checkpointing = "unsloth",
        random_state = 3407,
    )
    is_trained = False
    print("✅ Base 9B model loaded and blank LoRA adapters successfully attached.")

"""I can't just blindly feed a CSV into the trainer. If the generation script failed or the columns got messed up, the trainer will crash cryptically. I wrote strict guardrails here to verify the file exists, ensure the required columns are present, and drop any corrupted rows."""

import pandas as pd
from datasets import Dataset
import gc

if is_trained:
    print("✅ Model is already trained! Skipping dataset loading.")
else:
    csv_path = '/content/drive/MyDrive/my_dataset.csv'

    # GUARDRAIL 1: Check if file exists
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"CRITICAL ERROR: Cannot find {csv_path}. Did you finish the dataset generation phase?")

    print("Loading dataset from Drive...")
    try:
        df = pd.read_csv(csv_path, on_bad_lines='skip')
    except Exception as e:
        raise RuntimeError(f"CRITICAL ERROR: Failed to read the CSV file. Details: {e}")

    # GUARDRAIL 2: Verify column integrity
    if 'input' not in df.columns or 'output' not in df.columns:
        raise ValueError("CRITICAL ERROR: The CSV is missing 'input' or 'output' columns. Please check the dataset format.")

    # GUARDRAIL 3: Clean corrupted data
    initial_row_count = len(df)
    df = df.dropna(subset=['input', 'output'])
    dropped_rows = initial_row_count - len(df)
    if dropped_rows > 0:
        print(f"Warning: Dropped {dropped_rows} corrupted or empty rows from the dataset.")

    if df.empty:
        raise ValueError("CRITICAL ERROR: The dataset is completely empty after cleaning. Cannot proceed with training.")

    raw_data = df.to_dict(orient="records")

    # Formatting to match Gemma's expected chat structure
    # ADDED: Explicitly telling the AI to expect Tagalog, Bisaya, and English mixtures.
    prompt_template = """<start_of_turn>user
You are an expert editor. Clean this raw Philippine speech transcript by removing stutters, false starts, and local filler words (ano, kuan, bale) while preserving the original meaning.
The text may be in Tagalog, Bisaya, English, or a mixture of the three. Keep the original language mixture intact.

Transcript: {input}<end_of_turn>
<start_of_turn>model
{output}<end_of_turn>"""

    def format_dataset(examples):
        texts = []
        for i, o in zip(examples["input"], examples["output"]):
            text = prompt_template.format(input=i, output=o) + tokenizer.eos_token
            texts.append(text)
        return {"text": texts}

    dataset = Dataset.from_list(raw_data)
    formatted_dataset = dataset.map(format_dataset, batched=True)

    # OPTIMIZATION: Delete intermediate data structures to instantly free up CPU RAM
    del df, raw_data, dataset
    gc.collect()

    print(f"Successfully validated, loaded, and formatted training pairs.")

"""This is the riskiest part of the pipeline. Because I upgraded to the massive 9B model, I lowered the per_device_train_batch_size to 1 and increased the gradient accumulation to 8. This guarantees it will still fit comfortably inside the free T4 GPU's 15GB VRAM limit without triggering an Out-of-Memory (OOM) crash during backpropagation."""

import gc
from trl import SFTTrainer
from transformers import TrainingArguments

if is_trained:
    print("✅ Model is already trained! Skipping the SFT training loop.")
else:
    # GUARDRAIL 4: Flush GPU memory before training begins
    gc.collect()
    torch.cuda.empty_cache()

    trainer = SFTTrainer(
        model = model,
        tokenizer = tokenizer,
        train_dataset = formatted_dataset,
        dataset_text_field = "text",
        max_seq_length = max_seq_length,
        dataset_num_proc = 2,
        args = TrainingArguments(
            per_device_train_batch_size = 1,
            gradient_accumulation_steps = 8,
            warmup_steps = 20,
            num_train_epochs = 2,
            learning_rate = 2e-4,
            fp16 = True,
            bf16 = False,
            logging_steps = 5,
            optim = "adamw_8bit",
            weight_decay = 0.01,
            lr_scheduler_type = "cosine",
            seed = 3407,
            output_dir = "outputs",
        ),
    )

    print("Starting Optimized Supervised Fine-Tuning (SFT)...")

    try:
        trainer_stats = trainer.train()
        print("Training complete. Neural weights updated successfully.")
    except RuntimeError as e:
        if "out of memory" in str(e).lower():
            print("\n❌ CRITICAL OOM ERROR: The GPU ran out of memory during training.")
            print("FIX: Check your batch size parameters.")
        raise e
    finally:
        # OPTIMIZATION: Instantly delete the trainer and its 8GB of optimizer states
        if 'trainer' in locals() or 'trainer' in globals():
            del trainer
        gc.collect()
        torch.cuda.empty_cache()
        print("✅ Optimizer memory freed.")

"""I use os.makedirs with exist_ok=True to ensure the directory is created properly before saving. Wrapping this in an exception handler ensures I know exactly if and why saving to Google Drive failed."""

import os

if is_trained:
    print("✅ Model weights are already secured in Google Drive. Skipping save.")
else:
    save_path = "/content/drive/MyDrive/ph_stutter_smoother_lora"

    # GUARDRAIL 5: Safely ensure the target directory exists
    os.makedirs(save_path, exist_ok=True)

    try:
        print(f"Saving custom LoRA adapters to {save_path}...")
        model.save_pretrained(save_path)
        tokenizer.save_pretrained(save_path)
        print("Model weights safely secured in Google Drive.")

        # Now mark as trained so future "Run All" commands skip the loop!
        is_trained = True
    except Exception as e:
        print(f"❌ CRITICAL ERROR: Failed to save weights to Drive. Make sure you have enough storage space. Details: {e}")

"""I am building a custom frontend separately, I don't need a fancy UI here. Instead, I am turning this Colab notebook into a pure Backend API. The script accepts audio file uploads directly from my custom website, processes the audio synchronously using Whisper and Gemma, and securely exposes a /process_audio endpoint."""

# --- THE BACKEND API SERVER ---
import gradio as gr
from faster_whisper import WhisperModel
import torch
import gc
from unsloth import FastLanguageModel

print("Purging any remaining setup memory to make room for Whisper...")

# AGGRESSIVE VRAM PURGE (Global)
if 'formatted_dataset' in globals():
    del formatted_dataset

gc.collect()
torch.cuda.empty_cache()

print("Initializing local Backend API server...")

# 1. Load Whisper into the T4 GPU using Faster-Whisper
audio_model = WhisperModel("large-v3", device="cuda", compute_type="int8")

# 2. Switch Gemma into super-fast inference mode
FastLanguageModel.for_inference(model)

def process_audio_api(audio_filepath):
    """
    This Generator API is designed for LIMITLESS audio.
    It loops through audio chunks one-by-one with internal failsafes to guarantee
    a single bad token won't crash a 2-hour podcast transcription midway through!
    """
    if audio_filepath is None:
        yield "", "", "Error: No audio file provided."
        return

    full_messy_text = ""
    full_clean_text = ""

    try:
        yield "Starting...", "Waiting for Gemma...", "Status: Analyzing podcast timeline..."

        dynamic_hint = "A conversation using a mixture of Tagalog, Bisaya, and English discussing various mixed topics."

        # 'segments' is a Python Generator. It yields chunks of audio on the fly!
        segments, info = audio_model.transcribe(
            audio_filepath,
            condition_on_previous_text=False,
            language="tl",
            beam_size=5,
            initial_prompt=dynamic_hint
        )

        # THE LIMITLESS PROCESSING LOOP:
        for segment in segments:
            # --- FAILSAFE: Chunk-Level Crash Prevention ---
            # If one 5-second chunk fails, we skip it and continue the podcast!
            try:
                messy_chunk = segment.text.strip()
                if not messy_chunk:
                    continue

                # 1. Append new raw text
                full_messy_text += messy_chunk + " "

                # 2. Tell the frontend we are processing this exact timestamp
                yield full_messy_text.strip(), full_clean_text.strip() + " [Smoothing...]", f"Status: Processing timestamp {segment.start:.2f}s to {segment.end:.2f}s"

                # 3. Clean ONLY this specific chunk with Gemma
                prompt = f"""<start_of_turn>user
You are an expert editor. Clean this raw Philippine speech transcript by removing stutters, false starts, and local filler words (ano, kuan, bale) while preserving the original meaning.
The text may be in Tagalog, Bisaya, English, or a mixture of the three. Keep the original language mixture intact.

Dynamically analyze the transcript to determine its context and mixed topics. Based on your analysis, aggressively correct any phonetic misspellings of English or Local words.

Transcript: {messy_chunk}<end_of_turn>
<start_of_turn>model\n"""

                # Fix for the "too many indices for tensor" error:
                # We use the raw tokenizer and explicitly pass input_ids and attention_mask to prevent tensor mismatch.
                inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

                outputs = model.generate(
                    input_ids=inputs.input_ids,
                    attention_mask=inputs.attention_mask,
                    max_new_tokens=256, 
                    use_cache=True,
                    pad_token_id=tokenizer.eos_token_id,
                    repetition_penalty=1.15,
                    temperature=0.3,
                    top_p=0.9
                )

                result_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
                clean_chunk = result_text.split("model\n")[-1].strip()

                # 4. Append the cleaned chunk
                full_clean_text += clean_chunk + " "

                # 5. Instantly yield the live update to the UI
                yield full_messy_text.strip(), full_clean_text.strip(), f"Status: Chunk mapped at {segment.end:.2f}s"

            except Exception as chunk_error:
                print(f"Skipping problematic chunk at {segment.start}s due to error: {chunk_error}")
                full_clean_text += f"[Unprocessable Chunk: {messy_chunk}] "
                continue # Gracefully moves to the next chunk without crashing!

            finally:
                # 6. Aggressive chunk-level memory cleanup
                if 'inputs' in locals(): del inputs
                if 'outputs' in locals(): del outputs
                gc.collect()
                torch.cuda.empty_cache()

        # When the loop finishes, the entire podcast is done!
        yield full_messy_text.strip(), full_clean_text.strip(), "Status: Podcast Processing Complete!"

    except Exception as e:
        print(f"Backend Processing Error: {e}")
        yield full_messy_text, full_clean_text, f"Status: [API Error] {e}"

# 3. Build the Headless API Interface
with gr.Blocks(theme=gr.themes.Monochrome()) as demo:
    gr.Markdown("### Limitless Backend API is Running")
    gr.Markdown("This interface handles endless chunked processing. Perfect for long podcasts.")

    with gr.Row():
        audio_in = gr.Audio(type="filepath", label="Upload Large Audio File (Tagalog/Bisaya/English)")

    submit_btn = gr.Button("Test Continuous Processing")

    with gr.Row():
        status_out = gr.Textbox(label="Live Backend Progress", value="Status: Waiting for input...", interactive=False)

    with gr.Row():
        raw_out = gr.Textbox(label="Raw Whisper Output", lines=8)
        clean_out = gr.Textbox(label="Gemma Smoothed Output", lines=8)

    # EXPOSING THE API ENDPOINT:
    submit_btn.click(
        fn=process_audio_api,
        inputs=[audio_in],
        outputs=[raw_out, clean_out, status_out],
        api_name="process_audio"
    )

print("Launching limitless backend API...")
demo.queue().launch(share=True, debug=True)